addSbtPlugin("org.scalameta"             % "sbt-scalafmt"  % "2.0.5")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"  % "0.1.8")
addSbtPlugin("com.eed3si9n"              % "sbt-buildinfo" % "0.9.0")
addSbtPlugin("com.dwijnand"              % "sbt-dynver"    % "4.0.0")
addSbtPlugin("com.jsuereth"              % "sbt-pgp"       % "1.1.2")
addSbtPlugin("org.xerial.sbt"            % "sbt-sonatype"  % "3.7")
