# Extracting dependency graph from sbt with: https://github.com/marketplace/actions/sbt-dependency-submission
name: Update Dependency Graph
on:
  push:
    branches:
      - main
      - master
      - cdk-master
jobs:
  dependency-graph:
    name: Update Dependency Graph
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: scalacenter/sbt-dependency-submission@v2.0.1